<?php
namespace app\common\controller;
use think\Controller;
use think\Db;
use think\response\View;
use think\Session;
use think\session\driver\Redis;

class Common extends Controller{
    public function _initialize()
    {
		
        parent::_initialize(); // TODO: Change the autogenerated stub
        $setconfig = setparma(1);
            if($setconfig['onoff'] == 0){
                $view = new \think\View();
               exit($view->fetch('common:info'));
            }
            if(!empty($uid = Session::get('uid'))){
                    $member_table = Db::name('member')->find($uid);
                    if(!$member_table){
                        $this->error('会员不存在','index/Login/index');
                    }
                    if($setconfig['chaoshi'] == 1){
                        $this->check_time();
                    }
            }else{
                $this->redirect(url('index/Login/index'));
            }
            $this->assign('data_s',$member_table);
    }
    //设置超时
    public function check_time(){
        $time = request()->time();
        $redis = new Redis();
        $oldtime = $redis->read('log_time');
        if(($time - $oldtime) > (60*20)){
                    $redis->destroy('uid');
           $this->error('登录超时','index1/login/index');
        }else{
             $redis->write('log_time',time());
        }
    }
}