<?php
namespace app\common\controller;
use think\Controller;
use think\Db;
use think\response\View;
use think\Session;

class Common extends Controller{
    public function _initialize()
    {
		
        parent::_initialize(); // TODO: Change the autogenerated stub
        $setconfig = setparma(1);
            if($setconfig['onoff'] == 0){
                $view = new \think\View();
               exit($view->fetch('common:info'));
            }
            if(!empty($uid = Session::get('uid'))){
                    $member_table = Db::name('member')->find($uid);
                    if(!$member_table){
                        $this->error('会员不存在','index/Login/index');
                    }
                    if($setconfig['chaoshi'] == 1){
                        $this->check_time();
                    }
            }else{
                $this->redirect('index/Login/index');
            }
            $this->assign('people_nums',file_get_contents('num.txt'));
            $member_table['old_logtime'] = Session::get('old_logtime')?:time();
            $this->assign('data_s',$member_table);
    }
    //设置超时
    public function check_time(){
        $time = request()->time();
        $oldtime = Session::get('log_time');
        if(($time - $oldtime) > (60*20)){
                    Session::clear('think');
           $this->error('登录超时','index1/login/index');
        }else{
             Session::set('log_time',$time);
        }
    }
}