<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/1/29 0029
 * Time: 下午 3:58
 */

namespace app\index\logic;


use think\Db;
use think\Model;

class User extends Model
{
    protected $table_object;//自定义表对象
    //计算迭代推荐人数
    public static function iteration($data){
        /**
         * @items 接收传过来的值 int
         * @uid 接收会员id int
         * **/
        $member = Db::name('member');//实例化一个会员表member
        $member_one = $member->where('id',$data['uid'])->find();
        $result_people = $member->where('recommend',$member_one['id'])->field('mobile,reg_time,id')->select();
        for($i=1;$i<11;$i++){
            if(!$result_people[0]['id']){
                return ['status'=>2,'msg'=>'暂无数据'];
            }
            if($i == $data['num']){
                return $result_people;
            }else{
                $result_people = $member->where('recommend',$result_people[0]['id'])->field('mobile,reg_time,id')->select();
            }
        }

    }
    //自定义初始化
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->table_object['member'] = new \app\index\model\User();//表示会员表
        $this->table_object['mp'] = Db::name('mp');//会员分红表
        $this->table_object['profit'] = Db::name('profit');//每日分红展示表
    }

    //定时每日分红
    public  function each_day_money(){
          $result_mp = $this->table_object['mp']->where(['type'=>1,'day_each'=>['egt','1']])->select();//首先查出所有的会员分红
           for ($i=0;$i<count($result_mp);$i++){//计算所有的会员分红
               $this->table_object['mp']->where('id',$result_mp[$i]['id'])->update([
                   'update_date'=>request()->time(),'day_each'=>$result_mp[$i]['day_each'] - 1,
                   'residue_money'=>$result_mp[$i]['each_money'] * ($result_mp[$i]['day_each'] - 1),//得到一个剩余金额
               ]);
                $this->table_object['profit']->insert([
                    'uid'=>$result_mp[$i]['uid'],
                    'create_time'=>time(),
                    'money'=>$result_mp[$i]['each_money'],
                    'order_id'=>$result_mp[$i]['order_id'],
                    'type'=>'1'//表示每日分红,这里也只分配每日分红
                ]);
                $this->table_object['member']->where(['id'=>$result_mp[$i]['uid'],'status'=>'1'])->setInc('money',$result_mp[$i]['each_money']);
           }
           exit;
    }
}