<?php

namespace app\index\model;

use think\Db;
use think\Model;
use think\Session;
use think\Url;
use think\Validate;

class User extends Model
{

    protected $table = 'web_member';
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

    }
}
